 C:/Users/Lilti/Documents/LEARNING/PROGRAMMING/z.2.Source_code/Python/Python_ATOM/Django_REST/recipe-app-api-advanced

docker-compose run --rm app sh -c "python manage.py test"


File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
      conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  django.db.utils.OperationalError: could not connect to server: Connection refused
         Is the server running on host "db" (172.23.0.2) and accepting
         TCP/IP connections on port 5432?
